#!/usr/bin/env bash
set -euo pipefail

# Interactive installer/setup wizard (CLI) for StoneGate bundles.
#
# This is meant for the *bundle installer*, not the frontend.
#
# It helps you:
# - pick a simulator backend port (default 8080)
# - set UI defaults (remote backend host/port, build-mode defaults)
# - install backend remotely via SSH (optional)
# - generate easy-to-edit scripts under generated/

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle_root="$(cd "$script_dir/.." && pwd)"

backend_port_default="8080"

prompt() {
  local msg="$1"; shift
  local def="${1:-}"
  local ans=""
  if [[ -n "$def" ]]; then
    read -r -p "$msg [$def]: " ans || true
    echo "${ans:-$def}"
  else
    read -r -p "$msg: " ans || true
    echo "$ans"
  fi
}

yesno() {
  local msg="$1"; shift
  local def="${1:-y}"
  local dshow="y/N"
  [[ "$def" == "y" ]] && dshow="Y/n"
  local ans
  ans="$(prompt "$msg" "$dshow")"
  if [[ "$ans" == "Y/n" || "$ans" == "y/N" ]]; then
    ans=""
  fi
  if [[ -z "$ans" ]]; then
    [[ "$def" == "y" ]] && return 0 || return 1
  fi
  case "${ans,,}" in
    y|yes) return 0;;
    n|no) return 1;;
    *) return 1;;
  esac
}

ensure_generated_dir() {
  mkdir -p "$bundle_root/generated"
}

write_runtime_config() {
  local ws_url="$1"
  local build_mode="$2"
  local auto_backend_schematic="$3"

  local dist_cfg="$bundle_root/frontend/dist/stonegate-config.js"
  if [[ ! -d "$bundle_root/frontend/dist" ]]; then
    echo "UI dist not found at $bundle_root/frontend/dist" >&2
    return 1
  fi

  cat > "$dist_cfg" <<EOF
// Generated by stonegate-wizard
// You can edit this file to change default UI behavior.

globalThis.__STONEGATE_CONFIG__ = {
  ws_url: ${ws_url@Q},
  build_mode: ${build_mode},
  auto_backend_schematic: ${auto_backend_schematic},
}
EOF

  echo "Wrote UI runtime config: $dist_cfg"
}

write_generated_remote_backend_script() {
  local remote_prefix="$1"
  local port="$2"
  local sim_mode="$3"

  ensure_generated_dir

  local out="$bundle_root/generated/remote-backend-install.sh"
  local args=""
  if [[ "$sim_mode" == "true" ]]; then
    args="--sim"
  fi

  cat > "$out" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# StoneGate remote backend install script
# Generated by stonegate-wizard. Safe to edit.
#
# Run this script ON the backend machine.
# It assumes you have the StoneGate bundle extracted and you run it from the bundle root.

prefix=${remote_prefix@Q}
backend_port=${port@Q}
backend_args=${args@Q}

bundle_root="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
cd "\$bundle_root"

if [[ \$EUID -ne 0 ]]; then
  echo "Re-run with sudo (needs to install into \$prefix and systemd)." >&2
  exit 1
fi

mkdir -p "\$prefix"
rm -rf "\$prefix"/*
mkdir -p "\$prefix/backend" "\$prefix/shared/protocol" "\$prefix/systemd"

cp -a "\$bundle_root/backend/StoneGate" "\$prefix/backend/StoneGate"
cp -a "\$bundle_root/shared/protocol/DeviceGraph.json" "\$prefix/shared/protocol/DeviceGraph.json"
cp -a "\$bundle_root/shared/protocol/ComponentSchema.json" "\$prefix/shared/protocol/ComponentSchema.json"
cp -a "\$bundle_root/systemd/stonegate-backend.service" "\$prefix/systemd/stonegate-backend.service"

mkdir -p /etc/stonegate
cat > /etc/stonegate/stonegate.env <<ENV
# StoneGate service configuration
BACKEND_PORT=\$backend_port
BACKEND_ARGS=\$backend_args
ENV

install -m 0644 "\$prefix/systemd/stonegate-backend.service" /etc/systemd/system/stonegate-backend.service
systemctl daemon-reload
systemctl enable stonegate-backend.service
systemctl restart stonegate-backend.service

echo "Installed backend to \$prefix"
echo "Service: stonegate-backend.service"
echo "Config:  /etc/stonegate/stonegate.env"
EOF

  chmod +x "$out"
  echo "Generated: $out"
}

write_generated_ssh_push_script() {
  local ssh_host="$1"
  local remote_prefix="$2"
  local port="$3"
  local sim_mode="$4"

  ensure_generated_dir

  local out="$bundle_root/generated/push-backend-over-ssh.sh"
  local args=""
  if [[ "$sim_mode" == "true" ]]; then
    args="--sim"
  fi

  cat > "$out" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# StoneGate remote backend installer (SSH push)
# Generated by stonegate-wizard. Safe to edit.

ssh_host=${ssh_host@Q}
remote_prefix=${remote_prefix@Q}
backend_port=${port@Q}
backend_args=${args@Q}

bundle_root="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
cd "\$bundle_root"

tar -C "\$bundle_root" -cf - \
  backend/StoneGate \
  shared/protocol/DeviceGraph.json \
  shared/protocol/ComponentSchema.json \
  systemd/stonegate-backend.service \
  | ssh "\$ssh_host" "set -euo pipefail; sudo mkdir -p '\$remote_prefix'; sudo tar -C '\$remote_prefix' -xf -"

ssh "\$ssh_host" "set -euo pipefail;
  sudo mkdir -p /etc/stonegate;
  sudo tee /etc/stonegate/stonegate.env >/dev/null <<'ENV'
# StoneGate service configuration
BACKEND_PORT=\$backend_port
BACKEND_ARGS=\$backend_args
ENV
  sudo install -m 0644 '\$remote_prefix/systemd/stonegate-backend.service' /etc/systemd/system/stonegate-backend.service;
  sudo systemctl daemon-reload;
  sudo systemctl enable stonegate-backend.service;
  sudo systemctl restart stonegate-backend.service;
"
EOF

  chmod +x "$out"
  echo "Generated: $out"
}

remote_install_backend() {
  local ssh_host="$1"
  local remote_prefix="$2"
  local port="$3"
  local sim_mode="$4"

  local args=""
  if [[ "$sim_mode" == "true" ]]; then
    args="--sim"
  fi

  tar -C "$bundle_root" -cf - \
    backend/StoneGate \
    shared/protocol/DeviceGraph.json \
    shared/protocol/ComponentSchema.json \
    systemd/stonegate-backend.service \
    | ssh "$ssh_host" "set -euo pipefail; sudo mkdir -p '$remote_prefix'; sudo tar -C '$remote_prefix' -xf -"

  ssh "$ssh_host" "set -euo pipefail;
    sudo mkdir -p /etc/stonegate;
    sudo tee /etc/stonegate/stonegate.env >/dev/null <<'ENV'
# StoneGate service configuration
BACKEND_PORT=${port}
BACKEND_ARGS=${args}
ENV
    sudo install -m 0644 '$remote_prefix/systemd/stonegate-backend.service' /etc/systemd/system/stonegate-backend.service;
    sudo systemctl daemon-reload;
    sudo systemctl enable stonegate-backend.service;
    sudo systemctl restart stonegate-backend.service;
  "
}

cat <<'EOF'
StoneGate setup wizard

Choose an installation scenario:
  1) Local portable (UI + simulator backend)
  2) Local UI only (connect to an existing backend)
  3) Install backend on a remote machine over SSH (and/or generate scripts)
  4) System install (systemd): backend only
  5) System install (systemd): UI only
  6) System install (systemd): backend + UI
EOF

choice="$(prompt "Enter choice" "1")"
backend_port="$(prompt "Backend port" "$backend_port_default")"

sim_mode=true
if yesno "Use simulator backend (--sim)?" "y"; then
  sim_mode=true
else
  sim_mode=false
fi

backend_host="localhost"
if [[ "$choice" == "2" || "$choice" == "5" ]]; then
  backend_host="$(prompt "Backend host (where StoneGate backend runs)" "localhost")"
fi

ws_url="ws://${backend_host}:${backend_port}/status"

build_mode=false
auto_backend_schematic=false
if yesno "Enable Build Mode UI defaults?" "n"; then
  build_mode=true
  auto_backend_schematic=true
fi

case "$choice" in
  1)
    write_runtime_config "$ws_url" "$build_mode" "$auto_backend_schematic"
    exec "$bundle_root/bin/stonegate-run" --sim
    ;;
  2)
    write_runtime_config "$ws_url" "$build_mode" "$auto_backend_schematic"
    exec "$bundle_root/bin/stonegate-run" --ui-only
    ;;
  3)
    ssh_host="$(prompt "SSH host (user@host)" "user@remote")"
    remote_prefix="$(prompt "Remote install dir" "/opt/stonegate")"

    if yesno "Generate editable install scripts under generated/?" "y"; then
      write_generated_remote_backend_script "$remote_prefix" "$backend_port" "$sim_mode"
      write_generated_ssh_push_script "$ssh_host" "$remote_prefix" "$backend_port" "$sim_mode"
      echo "Scripts written under: $bundle_root/generated/"
    fi

    if yesno "Run the SSH install now?" "y"; then
      remote_install_backend "$ssh_host" "$remote_prefix" "$backend_port" "$sim_mode"
      echo "Remote backend installed. Check: ssh $ssh_host systemctl status stonegate-backend.service"
    fi

    backend_host="$(prompt "What hostname should the UI use to reach the backend?" "${ssh_host#*@}")"
    ws_url="ws://${backend_host}:${backend_port}/status"
    if yesno "Configure and start local UI now?" "y"; then
      write_runtime_config "$ws_url" "$build_mode" "$auto_backend_schematic"
      exec "$bundle_root/bin/stonegate-run" --ui-only
    fi
    ;;
  4)
    sudo "$bundle_root/bin/install.sh" --mode systemd-backend
    ;;
  5)
    write_runtime_config "$ws_url" "$build_mode" "$auto_backend_schematic"
    sudo "$bundle_root/bin/install.sh" --mode systemd-ui
    ;;
  6)
    write_runtime_config "$ws_url" "$build_mode" "$auto_backend_schematic"
    sudo "$bundle_root/bin/install.sh" --mode systemd-full
    ;;
  *)
    echo "Unknown choice: $choice" >&2
    exit 2
    ;;
esac
