#!/usr/bin/env python3

"""Generate installable StoneGate SDK artifacts (Python + C++).

This repo keeps the *source of truth* for the SDK in:
  - stonegate_api.py
  - stonegate_qec.py
  - stonegate_api.hpp
    - stonegate_qec.hpp

Running this script will write a distributable layout under:
  - sdk/python/stonegate_sdk/
  - sdk/cpp/

Python usage (editable install):
  python3 tools/generate_stonegate_sdk.py
  python3 -m pip install -e sdk/python/stonegate_sdk

C++ usage (CMake install of headers):
  cmake -S sdk/cpp -B sdk/cpp/build
  cmake --build sdk/cpp/build
  cmake --install sdk/cpp/build --prefix sdk/cpp/_install

The goal is that notebooks/scripts import `stonegate_api` and `stonegate_qec`
without redefining convenience helpers.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_if_changed(path: Path, text: str) -> bool:
    if path.exists():
        try:
            if _read_text(path) == text:
                return False
        except Exception:
            pass
    _write_text(path, text)
    return True


def generate(*, repo_root: Path) -> list[Path]:
    changed: list[Path] = []

    api_py = repo_root / "stonegate_api.py"
    qec_py = repo_root / "stonegate_qec.py"
    api_hpp = repo_root / "stonegate_api.hpp"
    qec_hpp = repo_root / "stonegate_qec.hpp"

    missing = [p for p in (api_py, qec_py, api_hpp, qec_hpp) if not p.exists()]
    if missing:
        raise SystemExit(f"Missing required source files: {', '.join(str(p) for p in missing)}")

    sdk_py_root = repo_root / "sdk" / "python" / "stonegate_sdk"
    sdk_cpp_root = repo_root / "sdk" / "cpp"

    header = (
        "# Generated file.\n"
        "# Do not edit in sdk/. Edit the repo root sources instead:\n"
        "#   - stonegate_api.py\n"
        "#   - stonegate_qec.py\n"
        "#   - stonegate_api.hpp\n"
        "#   - stonegate_qec.hpp\n"
        "# Regenerate with: python3 tools/generate_stonegate_sdk.py\n\n"
    )

    # ---- Python (packages named stonegate_api / stonegate_qec)
    pyproject = """[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stonegate-sdk"
version = "0.0.0+local"
description = "StoneGate SDK helpers (generated from the StoneGate repo)"
requires-python = ">=3.10"
dependencies = ["websockets>=11"]

[tool.setuptools]
packages = ["stonegate_api", "stonegate_qec"]
"""

    readme = """# StoneGate SDK (generated)

This directory is generated by `tools/generate_stonegate_sdk.py`.

## Install (editable)

```bash
python3 -m pip install -e .
```

## Use

```python
import stonegate_api as sg
import stonegate_qec as qec

sg.WS_URL = "ws://localhost:8080/status"
```
"""

    # Convert the single-file modules into package __init__.py files.
    api_pkg = header + _read_text(api_py)
    qec_pkg = header + _read_text(qec_py)

    for p, t in [
        (sdk_py_root / "pyproject.toml", pyproject),
        (sdk_py_root / "README.md", readme),
        (sdk_py_root / "stonegate_api" / "__init__.py", api_pkg),
        (sdk_py_root / "stonegate_qec" / "__init__.py", qec_pkg),
    ]:
        if _write_if_changed(p, t):
            changed.append(p)

    # ---- C++
    hpp_text = (
        "// Generated file.\n"
        "// Do not edit in sdk/. Edit stonegate_api.hpp at repo root instead.\n"
        "// Regenerate with: python3 tools/generate_stonegate_sdk.py\n\n"
        + _read_text(api_hpp)
    )

    qec_hpp_text = (
        "// Generated file.\n"
        "// Do not edit in sdk/. Edit stonegate_qec.hpp at repo root instead.\n"
        "// Regenerate with: python3 tools/generate_stonegate_sdk.py\n\n"
        + _read_text(qec_hpp)
    )

    cpp_text = (
        "// Generated file.\n"
        "// This translation unit exists to make it easy to build/install the SDK as a library if desired.\n"
        "#include \"stonegate_api.hpp\"\n"
    )

    cmake = """cmake_minimum_required(VERSION 3.16)
project(stonegate_sdk LANGUAGES CXX)

add_library(stonegate_sdk INTERFACE)
target_include_directories(stonegate_sdk INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)

target_compile_features(stonegate_sdk INTERFACE cxx_std_17)

install(DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/include/ DESTINATION include)
"""

    for p, t in [
        (sdk_cpp_root / "include" / "stonegate_api.hpp", hpp_text),
        (sdk_cpp_root / "include" / "stonegate_qec.hpp", qec_hpp_text),
        (sdk_cpp_root / "src" / "stonegate_api.cpp", cpp_text),
        (sdk_cpp_root / "CMakeLists.txt", cmake),
    ]:
        if _write_if_changed(p, t):
            changed.append(p)

    return changed


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate StoneGate SDK artifacts")
    ap.add_argument(
        "--repo-root",
        default=None,
        help="Path to repo root (defaults to parent of tools/)",
    )
    args = ap.parse_args()

    tools_dir = Path(__file__).resolve().parent
    repo_root = Path(args.repo_root).resolve() if args.repo_root else tools_dir.parent

    changed = generate(repo_root=repo_root)
    if changed:
        print("Generated/updated:")
        for p in changed:
            print(f"- {p.relative_to(repo_root)}")
    else:
        print("SDK already up to date.")


if __name__ == "__main__":
    main()
